# Generated by Django 5.1.4 on 2025-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='customer/defaultavatar.jpeg', null=True, upload_to='customer/'),
        ),
    ]
