# Generated by Django 5.1.4 on 2025-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
