# Generated by Django 5.1.4 on 2025-03-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_complaint_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagepickup',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], default='cash', max_length=20),
        ),
    ]
