# Generated by Django 5.1.4 on 2025-03-04 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_garbagepickup_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagepickup',
            name='subscription_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
