# Generated by Django 5.1.4 on 2025-03-08 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0007_garbagepickup_subscription_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against_collector', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_complaints', to='customer.garbagepickup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
