# Generated by Django 5.1.4 on 2025-03-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
        ('gadmin', '0004_driverassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gadmin.driver'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
