# Generated by Django 5.1.4 on 2025-03-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_complaint_collector_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
