# Generated by Django 5.1.4 on 2025-03-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadmin', '0004_driverassigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycledProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='recycled_products/')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadmin.recycler')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_details', models.JSONField()),
                ('pickup_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_in_stock', 'Not in Stock')], default='pending', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadmin.recycler')),
            ],
        ),
    ]
