# Generated by Django 5.1.4 on 2025-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0001_initial'),
    ]

    operations = [
    ]
