# Generated by Django 5.1.4 on 2025-03-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0002_auto_20250312_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycledproducts',
            name='recycler',
        ),
    ]
