# Generated by Django 5.1.4 on 2025-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0003_remove_recycledproducts_recycler'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledproducts',
            name='supercoin_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
