# Generated by Django 5.1.4 on 2025-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0004_recycledproducts_supercoin_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledproducts',
            name='recycler_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
