# Generated by Django 5.1.4 on 2025-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0005_recycledproducts_recycler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycledproducts',
            name='recycler_id',
            field=models.PositiveIntegerField(),
        ),
    ]
