# Generated by Django 5.1.4 on 2025-03-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0006_alter_recycledproducts_recycler_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('recycler_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycler.recyclerrequests')),
            ],
        ),
    ]
