# Generated by Django 5.1.4 on 2025-03-13 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0008_remove_complaint_status_complaint_is_solved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycledproducts',
            name='recycler_id',
        ),
        migrations.AddField(
            model_name='recycledproducts',
            name='recycler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
