# Generated by Django 5.1.4 on 2025-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycler', '0009_remove_recycledproducts_recycler_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycledproducts',
            name='recycler',
        ),
        migrations.AddField(
            model_name='recycledproducts',
            name='recycler_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
