# Generated by Django 5.1.4 on 2025-03-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
