# Generated by Django 5.1.4 on 2025-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField()),
                ('driving_license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
