# Generated by Django 5.1.4 on 2025-03-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_garbagepickup_subscription_start_date'),
        ('gadmin', '0003_recycler_password_alter_recycler_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gadmin.driver')),
                ('garbage_pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.garbagepickup')),
            ],
        ),
    ]
